defaultDuration = 1000;

const defaultCreatures = [
  {
    name: "Kobold Codemancer",
    level: 3,
    health: 200,
    physical_power: 5,
    physical_resistance: 10,
    magical_power: 15,
    magical_resistance: 15,
    reward: 500,
    duration: defaultDuration,
    task_to_dmg: null,
  },
  {
    name: "Wind Elemental",
    level: 3,
    health: 200,
    physical_power: 5,
    physical_resistance: 10,
    magical_power: 15,
    magical_resistance: 15,
    reward: 500,
    duration: defaultDuration,
    task_to_dmg: null,
  },
  {
    name: "Werewolf",
    level: 5,
    health: 500,
    physical_power: 100,
    physical_resistance: 50,
    magical_power: 20,
    magical_resistance: 70,
    reward: 800,
    duration: defaultDuration,
    task_to_dmg: null,
  },
  {
    name: "Fatty Ooze",
    level: 5,
    health: 500,
    physical_power: 100,
    physical_resistance: 50,
    magical_power: 20,
    magical_resistance: 70,
    reward: 800,
    duration: defaultDuration,
    task_to_dmg: null,
  },
  {
    name: "Broomaster",
    level: 7,
    health: 800,
    physical_power: 100,
    physical_resistance: 50,
    magical_power: 20,
    magical_resistance: 70,
    reward: 1000,
    duration: defaultDuration,
    task_to_dmg: null,
  },
  {
    name: "Unbearable Bear",
    level: 8,
    health: 1300,
    physical_power: 100,
    physical_resistance: 50,
    magical_power: 20,
    magical_resistance: 70,
    reward: 1200,
    duration: defaultDuration,
    task_to_dmg: null,
  },
  {
    name: "Hivemother",
    level: 8,
    health: 1300,
    physical_power: 100,
    physical_resistance: 50,
    magical_power: 20,
    magical_resistance: 70,
    reward: 1200,
    duration: defaultDuration,
    task_to_dmg: null,
  },
  {
    name: "Fire Drake",
    level: 10,
    health: 1800,
    physical_power: 200,
    physical_resistance: 100,
    magical_power: 200,
    magical_resistance: 100,
    reward: 1500,
    duration: defaultDuration,
    task_to_dmg: null,
  },
  {
    name: "Sloth",
    level: 12,
    health: 2000,
    physical_power: 200,
    physical_resistance: 100,
    magical_power: 200,
    magical_resistance: 100,
    reward: 1800,
    duration: defaultDuration,
    task_to_dmg: null,
  },
  {
    name: "The Great Habitus",
    level: 15,
    health: 3000,
    physical_power: 200,
    physical_resistance: 100,
    magical_power: 200,
    magical_resistance: 100,
    reward: 2000,
    duration: defaultDuration,
    task_to_dmg: null,
  },
  {
    name: "Santa Clown",
    level: 20,
    health: 5000,
    physical_power: 200,
    physical_resistance: 100,
    magical_power: 200,
    magical_resistance: 100,
    reward: 2000,
    duration: defaultDuration,
    task_to_dmg: null,
  },
  {
    name: "Handless Horseman",
    level: 20,
    health: 5000,
    physical_power: 200,
    physical_resistance: 100,
    magical_power: 200,
    magical_resistance: 100,
    reward: 2000,
    duration: defaultDuration,
    task_to_dmg: null,
  },
]

module.exports = defaultCreatures;